// edit profile
export const SETNAMEREGISTER = 'SETNAMEREGISTER';
export const SETLASTNAMEREGISTER = 'SETLASTNAMEREGISTER';
export const SETEMAILREGISTER = 'SETEMAILREGISTER';
export const SETPHONEREGISTER = 'SETPHONEREGISTER';
export const SETPASSWORDREGISTER = 'SETPASSWORDREGISTER';
export const SETCONFRIMPASSWORDREGISTER = 'SETCONFRIMPASSWORDREGISTER';
export const SETADDRESS = 'SETADDRESS';
export const SETPOSTCODE = 'SETPOSTCODE';



// signin
export const TOGGLESIGNIN = 'TOGGLESIGNIN';
export const SIGNEDINMENU = 'SIGNEDINMENU';


// account page

export const FETCHWISHLIST = 'FETCHWISHLIST';
export const REMOVEWISHLIST = 'REMOVEWISHLIST';

export const GETUSERPROFILE = 'GETUSERPROFILE';
export const SENDUSERPROFILE = 'SENDUSERPROFILE';
// loader
export const SIGNUPLOADER = 'SIGNUPLOADER';


// reset password
export const GETEMAIL = 'GETEMAIL';
export const GETOLDPASS = 'GETOLDPASS';
export const GETCONFIRMPASS = 'GETCONFIRMPASS';
export const GETCONFIRMPASSWORD = 'GETCONFIRMPASSWORD';


// export const RESETPASSWORD = 'RESETPASSWORD';




// show spinner in account page
export const TOGGLESPPINER = 'TOGGLESPPINER';



// save Profile info
export const SAVEPROFILE = 'SAVEPROFILE';


// register
export const VALIDATIONEMAILREGISTER = 'VALIDATIONEMAILREGISTER';
export const VALIDATIONPASSREGISTER = 'VALIDATIONPASSREGISTER';
export const VALIDATIONCONFIRMREGISTER = 'VALIDATIONCONFIRMREGISTER';


// signin
export const VALIDATIONEMAILSIGNIN = 'VALIDATIONEMAILSIGNIN';
export const VALIDATIONPASSWORDSIGNIN = 'VALIDATIONPASSWORDSIGNIN';

// detailsPage
export const SETACTIVEACCORDEON = 'SETACTIVEACCORDEON';
// FETCH COMMENT
export const FETCHCOMMENT = 'FETCHCOMMENT';

// ORDER SECTION
export const INCREASECOUNT = 'INCREASECOUNT';
export const DECREASECOUNT = 'DECREASECOUNT';
// ADD TO CART
export const SELECTSIZE = 'SELECTSIZE';
export const SELECTCOLOR = 'SELECTCOLOR';
export const RESETDETAILSPAGESTORE = 'RESETDETAILSPAGESTORE';
export const GETDETAILSDATA = 'GETDETAILSDATA';
export const ADDERRORINCART = 'ADDERRORINCART';



// global action
export const SHOWLOADERINDETAILS = 'SHOWLOADERINDETAILS';
