// edit profile
export const SETNAMEREGISTER = 'SETNAMEREGISTER';
export const SETLASTNAMEREGISTER = 'SETLASTNAMEREGISTER';
export const SETEMAILREGISTER = 'SETEMAILREGISTER';
export const SETPHONEREGISTER = 'SETPHONEREGISTER';
export const SETPASSWORDREGISTER = 'SETPASSWORDREGISTER';
export const SETCONFRIMPASSWORDREGISTER = 'SETCONFRIMPASSWORDREGISTER';
export const SETADDRESS = 'SETADDRESS';
export const SETPOSTCODE = 'SETPOSTCODE';



// signin
export const TOGGLESIGNIN = 'TOGGLESIGNIN';


// account page

export const FETCHWISHLIST = 'FETCHWISHLIST';

// show spinner in account page
export const TOGGLESPPINER = 'TOGGLESPPINER';



// save Profile info
export const SAVEPROFILE = 'SAVEPROFILE';


// register
export const VALIDATIONEMAILREGISTER = 'VALIDATIONEMAILREGISTER';
export const VALIDATIONPASSREGISTER = 'VALIDATIONPASSREGISTER';
export const VALIDATIONCONFIRMREGISTER = 'VALIDATIONCONFIRMREGISTER';

// signin
export const VALIDATIONEMAILSIGNIN = 'VALIDATIONEMAILSIGNIN';
export const VALIDATIONPASSWORDSIGNIN = 'VALIDATIONPASSWORDSIGNIN';

